apiVersion: carto.run/v1alpha1
kind: Workload
metadata:
  name: external-server-xml
  labels:
    apps.tanzu.vmware.com/workload-type: web
    app.kubernetes.io/part-of: tanzu-java-web-app
    #apps.tanzu.vmware.com/has-tests: "true"
    #apis.apps.tanzu.vmware.com/register-api: "true"
spec:
  # build:
  #   env:
  #     - name: BP_JAVA_APP_SERVER
  #       value: tomcat
  #     - name: BP_TOMCAT_EXT_CONF_URI
  #       value: "https://s3.ap-northeast-2.amazonaws.com/hshin-share.s3.tanzukorea.xyz/tomcat-conf.tgz"
  source:
    git:
      url: https://github.com/haewons-tanzu/app-with-external-tomcat
      ref:
        branch: master